disabled_rules:
- trailing_whitespace
- large_tuple
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
type_body_length:
    warning: 500
    error: 1000
function_parameter_count:
    warning: 6
    error: 8
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
identifier_name:
    min_length: 1
trailing_comma:
    mandatory_comma: true
reporter: "xcode"
